export const SUGGESTED_QUESTIONS = [
  {
    category: 'Popular',
    icon: '🔥',
    questions: [
      'What are my rights if I am arrested?',
      'How do I file an FIR online?',
      'What is the process for filing a consumer complaint?',
      'How can I get free legal aid in India?',
    ],
  },
  {
    category: 'Property',
    icon: '🏠',
    questions: [
      'What are my rights as a tenant?',
      'How to check property documents before buying?',
      'What is RERA and how does it protect home buyers?',
      'How to resolve a property dispute?',
    ],
  },
  {
    category: 'Women\'s Rights',
    icon: '👩',
    questions: [
      'What protections exist against domestic violence?',
      'What is the POSH Act and how to file a complaint?',
      'What are the maternity benefit laws in India?',
      'How to file a dowry harassment complaint?',
    ],
  },
  {
    category: 'Cyber',
    icon: '💻',
    questions: [
      'What to do if I am a victim of online fraud?',
      'How to report cyber bullying or harassment?',
      'What are the laws around data privacy in India?',
      'How to file a cyber crime complaint?',
    ],
  },
];

export const RIGHTS_CATEGORIES = [
  {
    id: 'fundamental',
    title: 'Fundamental Rights',
    titleHi: 'मौलिक अधिकार',
    icon: '📜',
    description: 'Rights guaranteed by the Constitution of India under Part III',
    descriptionHi: 'भारत के संविधान के भाग III के तहत गारंटीकृत अधिकार',
    color: '#4338CA',
    topics: [
      'Right to Equality (Articles 14-18)',
      'Right to Freedom (Articles 19-22)',
      'Right against Exploitation (Articles 23-24)',
      'Right to Freedom of Religion (Articles 25-28)',
      'Cultural & Educational Rights (Articles 29-30)',
      'Right to Constitutional Remedies (Article 32)',
    ],
  },
  {
    id: 'consumer',
    title: 'Consumer Rights',
    titleHi: 'उपभोक्ता अधिकार',
    icon: '🛒',
    description: 'Rights under the Consumer Protection Act, 2019',
    descriptionHi: 'उपभोक्ता संरक्षण अधिनियम, 2019 के तहत अधिकार',
    color: '#059669',
    topics: [
      'Right to Safety',
      'Right to be Informed',
      'Right to Choose',
      'Right to be Heard',
      'Right to Seek Redressal',
      'Right to Consumer Education',
      'Filing Consumer Complaints Online (e-Daakhil)',
    ],
  },
  {
    id: 'worker',
    title: 'Worker Rights',
    titleHi: 'श्रमिक अधिकार',
    icon: '👷',
    description: 'Rights under various labour laws and codes',
    descriptionHi: 'विभिन्न श्रम कानूनों और संहिताओं के तहत अधिकार',
    color: '#D97706',
    topics: [
      'Minimum Wages Act',
      'Payment of Wages Act',
      'Employee Provident Fund (EPF)',
      'ESI (Employee State Insurance)',
      'Maternity Benefits',
      'Gratuity Rights',
      'Right against Unfair Dismissal',
      'Occupational Safety',
    ],
  },
  {
    id: 'women',
    title: 'Women\'s Rights',
    titleHi: 'महिला अधिकार',
    icon: '⚖️',
    description: 'Laws protecting women\'s rights and dignity',
    descriptionHi: 'महिलाओं के अधिकारों और गरिमा की रक्षा करने वाले कानून',
    color: '#DB2777',
    topics: [
      'Protection of Women from Domestic Violence Act, 2005',
      'Sexual Harassment at Workplace (POSH Act)',
      'Dowry Prohibition Act',
      'Maternity Benefit Act',
      'Equal Remuneration Act',
      'Hindu Succession Act (Equal Property Rights)',
      'Section 498A IPC (Cruelty by Husband)',
    ],
  },
  {
    id: 'rti',
    title: 'Right to Information',
    titleHi: 'सूचना का अधिकार',
    icon: '📋',
    description: 'RTI Act, 2005 — Your right to know',
    descriptionHi: 'सूचना का अधिकार अधिनियम, 2005 — आपका जानने का अधिकार',
    color: '#7C3AED',
    topics: [
      'How to file an RTI application',
      'What information can be sought',
      'Time limits for responses',
      'First & Second Appeals',
      'Online RTI filing process',
      'Exemptions under RTI',
    ],
  },
  {
    id: 'digital',
    title: 'Digital & Cyber Rights',
    titleHi: 'डिजिटल और साइबर अधिकार',
    icon: '🌐',
    description: 'Rights in the digital world under IT Act and related laws',
    descriptionHi: 'आईटी अधिनियम और संबंधित कानूनों के तहत डिजिटल दुनिया में अधिकार',
    color: '#0891B2',
    topics: [
      'Data Privacy and Protection',
      'Cyber Crime Reporting',
      'Online Fraud Protection',
      'Social Media Rights',
      'Right to be Forgotten',
      'Digital Signature Laws',
      'E-Commerce Consumer Rights',
    ],
  },
];

export const DOCUMENT_TEMPLATES = [
  {
    id: 'affidavit',
    title: 'Affidavit',
    titleHi: 'शपथ पत्र',
    icon: '📄',
    description: 'General purpose sworn statement',
    fields: ['Full Name', 'Father/Husband Name', 'Address', 'Purpose of Affidavit', 'Statement Details'],
  },
  {
    id: 'rental-agreement',
    title: 'Rental Agreement',
    titleHi: 'किराया समझौता',
    icon: '🏠',
    description: 'Standard rental/lease agreement',
    fields: ['Landlord Name', 'Tenant Name', 'Property Address', 'Monthly Rent', 'Security Deposit', 'Lease Duration', 'Start Date'],
  },
  {
    id: 'legal-notice',
    title: 'Legal Notice',
    titleHi: 'कानूनी नोटिस',
    icon: '⚠️',
    description: 'Formal legal notice for disputes',
    fields: ['Sender Name', 'Sender Address', 'Recipient Name', 'Recipient Address', 'Subject of Notice', 'Facts of the Case', 'Relief Sought'],
  },
  {
    id: 'consumer-complaint',
    title: 'Consumer Complaint',
    titleHi: 'उपभोक्ता शिकायत',
    icon: '🛒',
    description: 'Consumer forum complaint format',
    fields: ['Complainant Name', 'Opposite Party Name', 'Product/Service Details', 'Purchase Date', 'Amount Paid', 'Deficiency/Defect Details', 'Relief Sought'],
  },
  {
    id: 'rti-application',
    title: 'RTI Application',
    titleHi: 'सूचना का अधिकार आवेदन',
    icon: '📋',
    description: 'Right to Information application format',
    fields: ['Applicant Name', 'Address', 'Public Authority Name', 'Information Sought', 'Period of Information'],
  },
  {
    id: 'police-complaint',
    title: 'Police Complaint',
    titleHi: 'पुलिस शिकायत',
    icon: '🚔',
    description: 'Written complaint to police station',
    fields: ['Complainant Name', 'Address', 'Phone Number', 'Incident Date', 'Incident Location', 'Description of Incident', 'Accused Details (if known)'],
  },
  {
    id: 'power-of-attorney',
    title: 'Power of Attorney',
    titleHi: 'मुख्तारनामा',
    icon: '✍️',
    description: 'General/Special power of attorney',
    fields: ['Principal Name', 'Agent Name', 'Purpose', 'Powers Granted', 'Duration', 'Property Details (if applicable)'],
  },
  {
    id: 'bail-application',
    title: 'Bail Application',
    titleHi: 'जमानत अर्जी',
    icon: '🔓',
    description: 'Application for bail in court',
    fields: ['Applicant Name', 'Case Number', 'Section/Charges', 'Court Name', 'Date of Arrest', 'Grounds for Bail'],
  },
];

export const LEGAL_AID_RESOURCES = [
  {
    title: 'National Legal Services Authority (NALSA)',
    titleHi: 'राष्ट्रीय विधिक सेवा प्राधिकरण',
    phone: '15100',
    website: 'https://nalsa.gov.in',
    description: 'Free legal aid for eligible persons under Legal Services Authority Act, 1987',
  },
  {
    title: 'Tele-Law Service',
    titleHi: 'टेली-लॉ सेवा',
    phone: '1800-180-1950',
    website: 'https://tele-law.in',
    description: 'Free legal advice through video conferencing at Common Service Centres',
  },
  {
    title: 'Women Helpline',
    titleHi: 'महिला हेल्पलाइन',
    phone: '181',
    website: 'https://ncw.nic.in',
    description: 'National Commission for Women - 24/7 helpline for women in distress',
  },
  {
    title: 'Cyber Crime Helpline',
    titleHi: 'साइबर अपराध हेल्पलाइन',
    phone: '1930',
    website: 'https://cybercrime.gov.in',
    description: 'Report cyber crimes and online fraud',
  },
  {
    title: 'Consumer Helpline',
    titleHi: 'उपभोक्ता हेल्पलाइन',
    phone: '1800-11-4000',
    website: 'https://consumerhelpline.gov.in',
    description: 'National Consumer Helpline for consumer complaints and guidance',
  },
  {
    title: 'Child Helpline',
    titleHi: 'चाइल्ड हेल्पलाइन',
    phone: '1098',
    website: 'https://childlineindia.org',
    description: '24/7 helpline for children in need of care and protection',
  },
  {
    title: 'Police Emergency',
    titleHi: 'पुलिस आपातकालीन',
    phone: '100 / 112',
    website: '',
    description: 'Emergency police assistance',
  },
  {
    title: 'e-Courts Services',
    titleHi: 'ई-कोर्ट सेवाएं',
    phone: '',
    website: 'https://ecourts.gov.in',
    description: 'Check case status, cause lists, and court orders online',
  },
];

export const STATE_LEGAL_AID = [
  { state: 'Andhra Pradesh', authority: 'AP State Legal Services Authority', phone: '040-23442685', website: 'https://apslsa.ap.gov.in' },
  { state: 'Bihar', authority: 'Bihar State Legal Services Authority', phone: '0612-2219540', website: 'https://bslsa.bih.nic.in' },
  { state: 'Delhi', authority: 'Delhi State Legal Services Authority', phone: '011-23385023', website: 'https://dslsa.org' },
  { state: 'Gujarat', authority: 'Gujarat State Legal Services Authority', phone: '079-27913694', website: 'https://gujslsa.gujarat.gov.in' },
  { state: 'Karnataka', authority: 'Karnataka State Legal Services Authority', phone: '080-22111700', website: 'https://kslsa.kar.nic.in' },
  { state: 'Kerala', authority: 'Kerala State Legal Services Authority', phone: '0471-2334908', website: 'https://kelsa.nic.in' },
  { state: 'Madhya Pradesh', authority: 'MP State Legal Services Authority', phone: '0755-2572684', website: 'https://mpslsa.gov.in' },
  { state: 'Maharashtra', authority: 'Maharashtra State Legal Services Authority', phone: '022-22617897', website: 'https://mahalsa.gov.in' },
  { state: 'Rajasthan', authority: 'Rajasthan State Legal Services Authority', phone: '0141-2227481', website: 'https://rlsa.gov.in' },
  { state: 'Tamil Nadu', authority: 'Tamil Nadu State Legal Services Authority', phone: '044-25341552', website: 'https://tnslsa.gov.in' },
  { state: 'Uttar Pradesh', authority: 'UP State Legal Services Authority', phone: '0522-2614862', website: 'https://upslsa.up.nic.in' },
  { state: 'West Bengal', authority: 'West Bengal State Legal Services Authority', phone: '033-22435842', website: 'https://wbslsa.gov.in' },
];

export const NAV_LINKS = [
  { href: '/', label: 'Home', labelHi: 'होम', icon: 'Home' },
  { href: '/chat', label: 'Legal Chat', labelHi: 'कानूनी चैट', icon: 'MessageSquare' },
  { href: '/analyze', label: 'Analyze Document', labelHi: 'दस्तावेज़ विश्लेषण', icon: 'FileSearch' },
  { href: '/generate', label: 'Generate Document', labelHi: 'दस्तावेज़ बनाएं', icon: 'FilePlus' },
  { href: '/rights', label: 'Know Your Rights', labelHi: 'अपने अधिकार जानें', icon: 'Scale' },
  { href: '/legal-aid', label: 'Legal Aid', labelHi: 'कानूनी सहायता', icon: 'LifeBuoy' },
];
